### ISSUE TITLE
Select vault(=set of credentials to be decrypted) according to envvars

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/sopsed#2]
Probably with `.sopsed.yaml` like:

```yaml
vaults:
  test:
    enabled_if:
      envvars:
        ENV: test
    subvaults: ./environments/test/.sopsed.test.yaml.enc
```

whereas decrypted `.sopsed.test.yaml` is:

```yaml
envvars:
  KUBECONFIG: ./kubeconfig
files:
- path_pattern: credentials/*-key.pem
```

which generates `.sopsed.test.vault.yaml`,

so that e.g. `ENV=test helmfile sync` only triggers decryption necessary to work on the test env.

**Comment by mumoshu** [comment]
For more versatility, maybe:

`.sopsed.yaml`:

```yaml
vaults:
  # Vault containing KUBECONFIG=environments/test/kubeconfig and the encrypted version of kubeconfig
  kube-test:
    # With SOPSED_COMMAND envvar populated and visible to the script
    enabled_if:
    - ./scripts/env_is test
    - [ "$SOPSED_COMMAND" == "kubectl" ];
    path: ./environments/test/.sopsed.vault.kube.yaml.enc
  # Vault containing KUBECONFIG=environments/prod/kubeconfig and the encrypted version of kubeconfig
  kube-prod:
    enabled_if:
    - ./scripts/env_is prod
    - [ "$SOPSED_COMMAND" == "kubectl" ];
    path: ./environments/prod/.sopsed.vault.kube.yaml.enc
```

Usage:

```
# This runs the kubectl command inside the "test" vault in which KUBECONFIG envvar is populated and the kubeconfig file is there decrypted
$ ENV=test sopsed kubectl get po

# This runs the kubectl command inside the "prod" vault in which KUBECONFIG envvar is populated and the kubeconfig file is there decrypted
$ ENV=prod sopsed kubectl get po
```
